services:
  - type: web
    name: discord-ticket-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DB_PATH
        value: ticket_bot.db
      - key: GUILD_ID
        value: ""
      - key: KEEP_ALIVE
        value: "true"
      - key: PORT
        value: "8080"
      - key: PYTHON_VERSION
        value: "3.11.9"
